title: The Nifty Chips Laboratory
logo: /assets/img/nifty_logo.png
description: The Nifty Chips Laboratory at Hanyang University is working on cool circuits and their automatic generators. This website is currently under construction.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
